run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 10m

linters:
  enable:
    - bodyclose
    - goimports
    - revive
    - gosec
    - misspell
    - nakedret
    - exportloopref
    - unconvert
    - unparam
    - whitespace
    - gocritic

issues:
  # include examples
  exclude-dirs-use-default: false

  exclude-dirs:
    - testdata$
    - test/mock

  exclude-files:
    - ".*\\.pb\\.go"

  exclude-rules:
    # exclude some lints from examples test files
    - path: examples_test.go
      linters:
        - staticcheck
        - ineffassign
        - govet

linters-settings:
  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0.0
  revive:
    rules:
      - name: unused-parameter
        disabled: true # It's useful to name parameters in library code for better readability
