#!/usr/bin/env bash
# Copies the test-support code shared by both modules from the lite module into
# the v2 module.
#
# Go's internal/ visibility rule is lexical on import paths, so packages under
# github.com/spiffe/go-spiffe/v2/... cannot import
# github.com/spiffe/go-spiffe/lite/internal/.... The lite module owns the
# canonical copy and this script regenerates the v2 one. `make generate-check`
# asserts the working tree is clean afterwards, so drift fails CI.
#
# Only the internal/ import paths are rewritten. The copies keep importing the
# lite module's public packages directly, which is fine because the v2 packages
# are type aliases for them.

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

sync() {
	local src=$1 dst=$2
	mkdir -p "$(dirname "${dst}")"
	{
		echo "// Code generated by \"make generate\"; DO NOT EDIT."
		echo "// Source: ${src}"
		echo
		sed -e 's|github.com/spiffe/go-spiffe/lite/internal/|github.com/spiffe/go-spiffe/v2/internal/|g' "${src}"
	} >"${dst}"
	echo "generated ${dst} from ${src}"
}

sync lite/internal/test/ca.go internal/test/ca.go
sync lite/internal/test/keys.go internal/test/keys.go
sync lite/internal/x509util/util.go internal/x509util/util.go
sync lite/internal/pemutil/pem.go internal/pemutil/pem.go
