// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.30.2
// source: reference.proto

package reference

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The WorkloadPIDReference message conveys a process id reference of a workload
// running in the same environment.
type WorkloadPIDReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The process id of the workload. MUST be a positive integer.
	Pid           int32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadPIDReference) Reset() {
	*x = WorkloadPIDReference{}
	mi := &file_reference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadPIDReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadPIDReference) ProtoMessage() {}

func (x *WorkloadPIDReference) ProtoReflect() protoreflect.Message {
	mi := &file_reference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadPIDReference.ProtoReflect.Descriptor instead.
func (*WorkloadPIDReference) Descriptor() ([]byte, []int) {
	return file_reference_proto_rawDescGZIP(), []int{0}
}

func (x *WorkloadPIDReference) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// The KubernetesObjectType message identifies the type of a Kubernetes object
// by its plural name and API group. This avoids ambiguity between plurals that
// happen to contain dots (e.g., the plural `myresource.example` in the `com`
// group vs. `myresource` in the `example.com` group) that arises when the
// `<plural>.<group>` shorthand is parsed as a single string.
type KubernetesObjectType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The plural name of the Kubernetes resource, as registered with
	// the Kubernetes API server. For example, `pods`, `deployments`, or the
	// plural form declared by a `CustomResourceDefinition`.
	Plural string `protobuf:"bytes,1,opt,name=plural,proto3" json:"plural,omitempty"`
	// Required. The API group of the Kubernetes resource. For non-core
	// resources this is the API group name (e.g., `apps`, `example.com`).
	// For core resources this field MUST be set to the literal string `core`.
	Group         string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesObjectType) Reset() {
	*x = KubernetesObjectType{}
	mi := &file_reference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesObjectType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesObjectType) ProtoMessage() {}

func (x *KubernetesObjectType) ProtoReflect() protoreflect.Message {
	mi := &file_reference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesObjectType.ProtoReflect.Descriptor instead.
func (*KubernetesObjectType) Descriptor() ([]byte, []int) {
	return file_reference_proto_rawDescGZIP(), []int{1}
}

func (x *KubernetesObjectType) GetPlural() string {
	if x != nil {
		return x.Plural
	}
	return ""
}

func (x *KubernetesObjectType) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

// The KubernetesObjectKey message identifies a specific Kubernetes object
// within its type by `namespace` and `name`.
type KubernetesObjectKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. The namespace of the referenced Kubernetes object. MUST be set
	// for namespaced resources. MUST be empty when the resource is
	// cluster-scoped.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Required. The name of the referenced Kubernetes object.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesObjectKey) Reset() {
	*x = KubernetesObjectKey{}
	mi := &file_reference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesObjectKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesObjectKey) ProtoMessage() {}

func (x *KubernetesObjectKey) ProtoReflect() protoreflect.Message {
	mi := &file_reference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesObjectKey.ProtoReflect.Descriptor instead.
func (*KubernetesObjectKey) Descriptor() ([]byte, []int) {
	return file_reference_proto_rawDescGZIP(), []int{2}
}

func (x *KubernetesObjectKey) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KubernetesObjectKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The KubernetesObjectReference message conveys a reference to an arbitrary
// Kubernetes object (built-in or custom) by which a workload is identified for
// the purpose of SVID issuance. The referenced object MUST exist and be accessible
// at the time of the request.
//
// The mapping from a Kubernetes object to a SPIFFE ID is implementation-defined;
// this specification does not mandate a particular SPIFFE ID format.
type KubernetesObjectReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The type of the referenced Kubernetes object.
	Type *KubernetesObjectType `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Optional. The namespaced name of the referenced Kubernetes object.
	// At least one of `key` or `uid` MUST be specified.
	Key *KubernetesObjectKey `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Optional. The UID of the referenced Kubernetes object. MUST be a valid
	// UUID string as assigned by Kubernetes. At least one of `key` or `uid`
	// MUST be specified. When both `key` and `uid` are specified, the server
	// MUST verify that the object resolved by `key` has the specified UID at
	// the time of issuing the SVIDs and MUST return an error otherwise.
	Uid           string `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesObjectReference) Reset() {
	*x = KubernetesObjectReference{}
	mi := &file_reference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesObjectReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesObjectReference) ProtoMessage() {}

func (x *KubernetesObjectReference) ProtoReflect() protoreflect.Message {
	mi := &file_reference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesObjectReference.ProtoReflect.Descriptor instead.
func (*KubernetesObjectReference) Descriptor() ([]byte, []int) {
	return file_reference_proto_rawDescGZIP(), []int{3}
}

func (x *KubernetesObjectReference) GetType() *KubernetesObjectType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *KubernetesObjectReference) GetKey() *KubernetesObjectKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KubernetesObjectReference) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

var File_reference_proto protoreflect.FileDescriptor

const file_reference_proto_rawDesc = "" +
	"\n" +
	"\x0freference.proto\x12\x10spiffe.reference\"(\n" +
	"\x14WorkloadPIDReference\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\"D\n" +
	"\x14KubernetesObjectType\x12\x16\n" +
	"\x06plural\x18\x01 \x01(\tR\x06plural\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\"G\n" +
	"\x13KubernetesObjectKey\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xa2\x01\n" +
	"\x19KubernetesObjectReference\x12:\n" +
	"\x04type\x18\x01 \x01(\v2&.spiffe.reference.KubernetesObjectTypeR\x04type\x127\n" +
	"\x03key\x18\x02 \x01(\v2%.spiffe.reference.KubernetesObjectKeyR\x03key\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\tR\x03uidBAZ?github.com/spiffe/go-spiffe/v2/proto/spiffe/reference;referenceb\x06proto3"

var (
	file_reference_proto_rawDescOnce sync.Once
	file_reference_proto_rawDescData []byte
)

func file_reference_proto_rawDescGZIP() []byte {
	file_reference_proto_rawDescOnce.Do(func() {
		file_reference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reference_proto_rawDesc), len(file_reference_proto_rawDesc)))
	})
	return file_reference_proto_rawDescData
}

var file_reference_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_reference_proto_goTypes = []any{
	(*WorkloadPIDReference)(nil),      // 0: spiffe.reference.WorkloadPIDReference
	(*KubernetesObjectType)(nil),      // 1: spiffe.reference.KubernetesObjectType
	(*KubernetesObjectKey)(nil),       // 2: spiffe.reference.KubernetesObjectKey
	(*KubernetesObjectReference)(nil), // 3: spiffe.reference.KubernetesObjectReference
}
var file_reference_proto_depIdxs = []int32{
	1, // 0: spiffe.reference.KubernetesObjectReference.type:type_name -> spiffe.reference.KubernetesObjectType
	2, // 1: spiffe.reference.KubernetesObjectReference.key:type_name -> spiffe.reference.KubernetesObjectKey
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_reference_proto_init() }
func file_reference_proto_init() {
	if File_reference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reference_proto_rawDesc), len(file_reference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reference_proto_goTypes,
		DependencyIndexes: file_reference_proto_depIdxs,
		MessageInfos:      file_reference_proto_msgTypes,
	}.Build()
	File_reference_proto = out.File
	file_reference_proto_goTypes = nil
	file_reference_proto_depIdxs = nil
}
